name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: GitHub Login
      run: docker login --username jvictormarques --password ${{ secrets.GHCR_PSWD }} ghcr.io

    - name: Generate TAG
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Build and Push the Docker image
      run: |
        docker build ./app --tag ghcr.io/joaoOrganization/react-image:latest
        docker tag ghcr.io/joaoOrganization/react-image:latest ghcr.io/joaoOrganization/react-image:${{ steps.generate_tag.outputs.sha }}
        docker push ghcr.io/joaoOrganization/react-image --all-tags